### ISSUE TITLE
"refined" leftovers

### ISSUE THREAD

**Issue by fregante** [ndom91/github-search-preview#1]
There's a lot of leftover code from Refined GitHub, you might want to drop all the CSS at least, to avoid conflicts: https://github.com/search?q=repo%3Andom91%2Fgithub-search-preview%20refined&type=code

**Comment by ndom91** [comment]
Yeah I just edited my comment on the original issue, I definitely plan on removing any left-over mentions of refined-github, including the logo, etc. Before making a release :pray:

**Comment by fregante** [comment]
And the "rgh" ID too https://github.com/search?q=repo%3Andom91%2Fgithub-search-preview+rgh&type=code

**Comment by ndom91** [comment]
Just got it into a "hey it works finally!" stage at this point :joy:

**Comment by ndom91** [comment]
Okay updated and removed all references, updated the logo, etc. 

Thanks again!

**Comment by fregante** [comment]
I think the welcome page should be dropped too since it's only needed for the token. It also has links to Refined GitHub's repo

**Comment by ndom91** [comment]
You mean the link to the security wiki page? I figured that's still useful and something anyone can link to, no?

My thinking was to keep the welcome screen, even though theres not much on it, because it's important in this use-case for folks to add a GH Token. It's easy to run out of the anonymous rate-limit on GitHub's API when browsing through search results and getting full files. 

I understand if this is all too similar to `refined-github`, however. What would you think if I remove that remaining security wiki link and redesign the welcome and options page a bit more to not look exactly like `refined-github`'s?

**Comment by fregante** [comment]
Oh I didn't realize that the api was still in use. 

You're free to copy the security page, but keeping a link to a different extension (Refined GitHub) is confusing for users. 

The style is fine
